# Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A

### 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [51]:
# list of 5 integers
integer_list = [125, 43, 102, 237, 23]
print(integer_list)

[125, 43, 102, 237, 23]

In [52]:
# append operation (adds to end of list)
integer_list.append(200)
print(integer_list)

[125, 43, 102, 237, 23, 200]

In [53]:
# extend operation - appends each element from argument list to end of integer_list
integer_list.extend([10,200])
print(integer_list)

[125, 43, 102, 237, 23, 200, 10, 200]

In [54]:
# insert operation - first argument is position in list, second is value to insert 
# this will insert in index 2 (3rd item in list)
integer_list.insert(2, 10)

In [55]:
print(integer_list)

[125, 43, 10, 102, 237, 23, 200, 10, 200]

In [56]:
# remove operation - removes the very first occurance of value that is passed as argument
integer_list.remove(10)
print(integer_list)
integer_list.remove(102)
print(integer_list)

[125, 43, 102, 237, 23, 200, 10, 200]
[125, 43, 237, 23, 200, 10, 200]

In [57]:
# remove last element at end of list
integer_list.pop()
print(integer_list)

[125, 43, 237, 23, 200, 10]

In [58]:
# clear - removes all elements from list
integer_list.clear()
print(integer_list)

[]

In [59]:
# index - returns the first index position of that element from that list
integer_list = [200, 12, 13, 12, 10, 90, 67, 10, 10]
print(integer_list.index(10)) # should be index 4
print(integer_list.index(12)) # should be index 1

4
1

In [60]:
# count - returns the number of elements with specified value (passed as argument)
print(integer_list.count(10)) # should print 3
print(integer_list.count(12)) # should print 2

3
2

In [61]:
# reverse method is used to reverse the order of the list
integer_list.reverse()
print(integer_list) # should print [10, 10, 67, 90, 10, 12, 13, 12, 200]

[10, 10, 67, 90, 10, 12, 13, 12, 200]

### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [62]:
student_names = ("Jameson", "Fake", "Morrison")
student_names[1] = "Clark"

TypeError: 'tuple' object does not support item assignment

**We get TypeError because tuple object is immutable and does not support assignment (changing values)**

### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [64]:
integer_set = {1, 10, 12, 10, 1, 19, 10, 12, 19}
print(integer_set)

{1, 10, 19, 12}

**Sets only hold distinct and unique values, which is why no duplicate values are displayed**

### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [65]:
person_dict = {'name' : 'Mahan', 'age': 45, 'city': 'Pune'}
person_dict['email'] = 'mahan@mail.com'
print(person_dict)

{'name': 'Mahan', 'age': 45, 'city': 'Pune', 'email': 'mahan@mail.com'}

### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [66]:
def is_able_to_vote(age: int) -> bool:
    if age < 0:
        raise ValueError("Negative age is not allowed. Please try again")
    return age >= 18

In [67]:
# test
print(is_able_to_vote(-19)) # less than 18, raise ValueError

ValueError: Negative age is not allowed. Please try again

In [68]:
print(is_able_to_vote(10)) # less than 18, false
print(is_able_to_vote(18)) # equal to 18, true
print(is_able_to_vote(50)) # greater than 18, true

False
True
True

### 6. Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [69]:
def print_grades(marks: int) -> str: 
    # order of if statements matter!
    # elif - else if i.e. "otherwise" => only executes this block if previous if statement is false
    # starting with Type Check and Value Error as marks are most likely between 0 - 100 (integer)
    # then goes on to check if >= 90, else check between 75-89, else check between 50-74, else check below 50
    if type(marks) is not int:
        raise TypeError("Marks are an integer grade from 0 to 100, please pass in an argument that is an integer")
    elif marks > 100:
        raise ValueError("Marks cannot be above 100. Marks are an integer grade from 0 to 100")
    elif 90 <= marks <= 100:
        print('A')
    elif marks >= 75:
        print('B')
    elif marks >= 50:
        print('C')
    else:
        print('Fail')

In [70]:
# Test
print_grades("Abhinav Thota") # should raise TypeError

TypeError: Marks are an integer grade from 0 to 100, please pass in an argument that is an integer

In [71]:
print_grades(120) # Should raise ValueError

ValueError: Marks cannot be above 100. Marks are an integer grade from 0 to 100

In [72]:
# test

print_grades(30) # Fail
print_grades(49) # Fail
print_grades(55) # C
print_grades(75) # B
print_grades(90) # A
print_grades(99) # A

Fail
Fail
C
B
A
A

#### 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [73]:
# wrote simple one line fns
def is_even(num : int) -> bool:
    '''checks if number is even'''
    # modulo returning 0 would mean no remainder when divided by two, hence number is even
    # else it would return 1, and that would be false (not even)
    return num % 2 == 0
def is_positive(num : int) -> bool:
    '''checks if number is positive'''
    return num > 0
def is_zero(num: int) -> bool:
    '''checks if number is zero'''
    return num == 0
def is_negative(num: int) -> bool:
    '''checks if number is negative'''
    return num < 0

def main(num : int):
    if is_positive(num):
        print (f"{num} is positive")
    if is_negative(num):
        print(f"{num} is negative")
    if is_zero(num):
        print(f"Number is zero")
    if is_even(num):
        print(f"{num} is even")

In [74]:
# test
main(0)
main(1)
main(120)
main(-2)

Number is zero
0 is even
1 is positive
120 is positive
120 is even
-2 is negative
-2 is even

## Section B: Numpy

In [79]:
import numpy as np

#### 8. Create:
- A scalar using np.array(5)

In [80]:
# scalar is zero dimensional array
scalar = np.array(5)
scalar.ndim # should return 0

0

- A 1D array with values 1 to 5

In [81]:
# used arange method to create, arguments in order are: start value, end value, step count (how much to increase with each element)
new_array = np.arange(1,6,1) 
new_array

array([1, 2, 3, 4, 5])

- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [82]:
new_2d_array = np.array([[10, 20, 30], [40, 50, 60]])
new_2d_array

array([[10, 20, 30],
       [40, 50, 60]])

#### 9. Generate a Numpy Array:
Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [83]:
# passed in size of array as keyword-argument in random.randint method
# each run of this cell will populate a 4*4 array with new random values
a = np.random.randint(0, 100, size=(4,4))
a

array([[81, 76, 27, 37],
       [28, 24,  7,  6],
       [72, 60, 71, 55],
       [21, 44, 24,  2]])

#### 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [84]:
import pandas as pd

In [85]:
# used reshape method to simply resize a 1d array into 3 * 3, could have also done it manually like before too
np_array = np.arange(1,10, 1).reshape(3,3)
df = pd.DataFrame(np_array, columns=["A", "B", "C"])

In [86]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## Exploring Pandas

#### 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:

In [87]:
# Create DataFrame - manually wrote each of the rows, 
# created some duplicate rows (Manish) and
# left some values blank for questions below
person_df = pd.DataFrame(
    [
     ["James", 64, "Miami", 400000],
     ["Alex", 49, "New York", 22000],
     ["Alex", 49, "New York", 22000],
     ["Shruti", 55, "Hyderabad", 8000],
     ["Marco", 28, "Milan", ],
     ["Nani", 37, "Chennai", 6000],
     ["Shreya", 40, "Miyapur", ],
     ["Rahul", 34, "Bengaluru", 10000],
     ["Rani", 25, "New Delhi", 8450],
     ["Zohran", 34, "Nashik", 45200],
     ["Manish", 18, "Jammu", 1200],
     ["Manish", 18, "Jammu", 1200],
     ["Manish", 18, "Jammu", 1200],
     ["Manish", 18, "Jammu", 1200],
    ],
    columns = ["Name", "Age", "City", "Salary"])

person_df

      Name  Age       City    Salary
0    James   64      Miami  400000.0
1     Alex   49   New York   22000.0
2     Alex   49   New York   22000.0
3   Shruti   55  Hyderabad    8000.0
4    Marco   28      Milan       NaN
5     Nani   37    Chennai    6000.0
6   Shreya   40    Miyapur       NaN
7    Rahul   34  Bengaluru   10000.0
8     Rani   25  New Delhi    8450.0
9   Zohran   34     Nashik   45200.0
10  Manish   18      Jammu    1200.0
11  Manish   18      Jammu    1200.0
12  Manish   18      Jammu    1200.0
13  Manish   18      Jammu    1200.0

- Use .info(), .describe()

In [88]:
person_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     14 non-null     int64
 2   City    14 non-null     str
 3   Salary  12 non-null     float64
dtypes: float64(1), int64(1), str(2)
memory usage: 580.0 bytes

In [89]:
person_df.describe()

             Age         Salary
count  14.000000      12.000000
mean   34.785714   43870.833333
std    15.110763  112892.709440
min    18.000000    1200.000000
25%    19.750000    1200.000000
50%    34.000000    8225.000000
75%    46.750000   22000.000000
max    64.000000  400000.000000

- Select 'Name' and 'City' columns

In [90]:
person_df['Name']

0      James
1       Alex
2       Alex
3     Shruti
4      Marco
5       Nani
6     Shreya
7      Rahul
8       Rani
9     Zohran
10    Manish
11    Manish
12    Manish
13    Manish
Name: Name, dtype: str

In [91]:
person_df['City']

0         Miami
1      New York
2      New York
3     Hyderabad
4         Milan
5       Chennai
6       Miyapur
7     Bengaluru
8     New Delhi
9        Nashik
10        Jammu
11        Jammu
12        Jammu
13        Jammu
Name: City, dtype: str

- Drop 'City' column

In [92]:
person_df = person_df.drop(columns = 'City')
person_df

      Name  Age    Salary
0    James   64  400000.0
1     Alex   49   22000.0
2     Alex   49   22000.0
3   Shruti   55    8000.0
4    Marco   28       NaN
5     Nani   37    6000.0
6   Shreya   40       NaN
7    Rahul   34   10000.0
8     Rani   25    8450.0
9   Zohran   34   45200.0
10  Manish   18    1200.0
11  Manish   18    1200.0
12  Manish   18    1200.0
13  Manish   18    1200.0

- Fill any missing values in 'Salary' column with the mean

In [93]:
# reassinging the Salary column with the values from a view generated by chaining the following functions:
# 1. fill all NaN/null values (fillna method) with the mean value of the column (mean method)
# 2. round it to 2 decimal places for formatting (round method)
person_df["Salary"] = person_df["Salary"].fillna(person_df['Salary'].mean()).round(2)
person_df

      Name  Age     Salary
0    James   64  400000.00
1     Alex   49   22000.00
2     Alex   49   22000.00
3   Shruti   55    8000.00
4    Marco   28   43870.83
5     Nani   37    6000.00
6   Shreya   40   43870.83
7    Rahul   34   10000.00
8     Rani   25    8450.00
9   Zohran   34   45200.00
10  Manish   18    1200.00
11  Manish   18    1200.00
12  Manish   18    1200.00
13  Manish   18    1200.00

- Remove any duplicate rows

In [94]:
person_df = person_df.drop_duplicates()
person_df

      Name  Age     Salary
0    James   64  400000.00
1     Alex   49   22000.00
3   Shruti   55    8000.00
4    Marco   28   43870.83
5     Nani   37    6000.00
6   Shreya   40   43870.83
7    Rahul   34   10000.00
8     Rani   25    8450.00
9   Zohran   34   45200.00
10  Manish   18    1200.00